
package com.doomTechnologies.view;


import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maycol
 */
public class GestionarMaterias extends javax.swing.JPanel {


    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    DefaultTableModel modelo3 = new DefaultTableModel();

    public GestionarMaterias() {
        initComponents();
        cargarTablaDocente();
        cargarTablaMateria();
        cargarTablaMateriaDocente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedGestionarMaterias = new javax.swing.JTabbedPane();
        jPanelMenuGestion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnPrinRegistrarMateria = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jBtnListarMaterias = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jBtnprinAsignarMateriDocente = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jBtnPrinListarMatDoc = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanelAsignarDocente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDocentesAsig = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMateriaAsig = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBtnBuscarDocenteAsig = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTxtBuscarNombreMateria = new javax.swing.JTextField();
        jButtonBuscarMateriaAsig = new javax.swing.JButton();
        jTxtBuscarDniDocente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtDniDocenteAsig = new javax.swing.JTextField();
        jTxtNombreAsig = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtApPaternoAsig = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtIdAsig = new javax.swing.JTextField();
        jTxtNombreAsigCurso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelListaMateriasDocente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListaMateriasDocente = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jTxtRegistroMateriaDocente = new javax.swing.JTextField();
        jBtnEliminarRegistro = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(928, 721));
        setPreferredSize(new java.awt.Dimension(928, 721));

        jTabbedGestionarMaterias.setMinimumSize(new java.awt.Dimension(928, 721));
        jTabbedGestionarMaterias.setPreferredSize(new java.awt.Dimension(928, 721));
        jTabbedGestionarMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedGestionarMateriasMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIONAR MATERIAS");

        jPanel1.setMinimumSize(new java.awt.Dimension(175, 180));
        jPanel1.setPreferredSize(new java.awt.Dimension(175, 180));

        jBtnPrinRegistrarMateria.setText("Registrar Materia");
        jBtnPrinRegistrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrinRegistrarMateriaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("REGISTRO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnPrinRegistrarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPrinRegistrarMateria)
                .addContainerGap())
        );

        jPanel7.setMinimumSize(new java.awt.Dimension(175, 180));
        jPanel7.setPreferredSize(new java.awt.Dimension(175, 180));

        jBtnListarMaterias.setText("Lista de Materias");
        jBtnListarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarMateriasActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LISTA MAT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnListarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnListarMaterias)
                .addContainerGap())
        );

        jPanel8.setMinimumSize(new java.awt.Dimension(175, 180));
        jPanel8.setPreferredSize(new java.awt.Dimension(175, 180));

        jBtnprinAsignarMateriDocente.setText("Asignar Docente");
        jBtnprinAsignarMateriDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnprinAsignarMateriDocenteActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ASIGNAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnprinAsignarMateriDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnprinAsignarMateriDocente)
                .addContainerGap())
        );

        jPanel9.setMinimumSize(new java.awt.Dimension(175, 180));
        jPanel9.setPreferredSize(new java.awt.Dimension(175, 180));

        jBtnPrinListarMatDoc.setText("Lista de Materias-Docente");
        jBtnPrinListarMatDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrinListarMatDocActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("LISTA DOC");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnPrinListarMatDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPrinListarMatDoc)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMenuGestionLayout = new javax.swing.GroupLayout(jPanelMenuGestion);
        jPanelMenuGestion.setLayout(jPanelMenuGestionLayout);
        jPanelMenuGestionLayout.setHorizontalGroup(
            jPanelMenuGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMenuGestionLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(jPanelMenuGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanelMenuGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanelMenuGestionLayout.setVerticalGroup(
            jPanelMenuGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuGestionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanelMenuGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(jPanelMenuGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedGestionarMaterias.addTab("Menu Gestion", jPanelMenuGestion);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Asignar docente");

        jTableDocentesAsig.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dni", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDocentesAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDocentesAsigMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDocentesAsig);

        jTableMateriaAsig.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nombre"
            }
        ));
        jTableMateriaAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMateriaAsigMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMateriaAsig);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Docente");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Materia");

        jLabel5.setText("Dni");

        jBtnBuscarDocenteAsig.setText("Buscar");
        jBtnBuscarDocenteAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarDocenteAsigActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre");

        jButtonBuscarMateriaAsig.setText("Buscar");
        jButtonBuscarMateriaAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarMateriaAsigActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Asignacion");

        jLabel8.setText("Dni Docente");

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel11.setText("Id Curso");

        jLabel12.setText("Nombre Curso");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAsignarDocenteLayout = new javax.swing.GroupLayout(jPanelAsignarDocente);
        jPanelAsignarDocente.setLayout(jPanelAsignarDocenteLayout);
        jPanelAsignarDocenteLayout.setHorizontalGroup(
            jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsignarDocenteLayout.createSequentialGroup()
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                                .addComponent(jTxtBuscarDniDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnBuscarDocenteAsig, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                                .addComponent(jTxtBuscarNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBuscarMateriaAsig, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                    .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTxtDniDocenteAsig))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNombreAsig)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtApPaternoAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtIdAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTxtNombreAsigCurso))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanelAsignarDocenteLayout.setVerticalGroup(
            jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBuscarDocenteAsig)
                            .addComponent(jTxtBuscarNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarMateriaAsig)
                            .addComponent(jTxtBuscarDniDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtDniDocenteAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsignarDocenteLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtNombreAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtApPaternoAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtIdAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsignarDocenteLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAsignarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNombreAsigCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedGestionarMaterias.addTab("Asignar Docente", jPanelAsignarDocente);

        jTableListaMateriasDocente.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Registro", "Dni Docente", "Nombre Docente", "Nombre Materia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaMateriasDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaMateriasDocenteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableListaMateriasDocente);

        jLabel13.setText("Id de Registro");

        jBtnEliminarRegistro.setText("Eliminar Registro");
        jBtnEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaMateriasDocenteLayout = new javax.swing.GroupLayout(jPanelListaMateriasDocente);
        jPanelListaMateriasDocente.setLayout(jPanelListaMateriasDocenteLayout);
        jPanelListaMateriasDocenteLayout.setHorizontalGroup(
            jPanelListaMateriasDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
            .addGroup(jPanelListaMateriasDocenteLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(jPanelListaMateriasDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtRegistroMateriaDocente)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jBtnEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelListaMateriasDocenteLayout.setVerticalGroup(
            jPanelListaMateriasDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaMateriasDocenteLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelListaMateriasDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelListaMateriasDocenteLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtRegistroMateriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnEliminarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedGestionarMaterias.addTab("Lista de  Materias-docente", jPanelListaMateriasDocente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedGestionarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedGestionarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPrinListarMatDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrinListarMatDocActionPerformed
        jTabbedGestionarMaterias.setSelectedIndex(2);
    }//GEN-LAST:event_jBtnPrinListarMatDocActionPerformed

    private void jBtnPrinRegistrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrinRegistrarMateriaActionPerformed
//        RegistroMaterias rm = new RegistroMaterias();
//        rm.setLocationRelativeTo(null);
//        rm.setVisible(true);
    }//GEN-LAST:event_jBtnPrinRegistrarMateriaActionPerformed

    private void jBtnListarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarMateriasActionPerformed
        ListaMaterias lM = new ListaMaterias();
        lM.setLocationRelativeTo(null);
        lM.setVisible(true);

    }//GEN-LAST:event_jBtnListarMateriasActionPerformed

    private void jBtnprinAsignarMateriDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnprinAsignarMateriDocenteActionPerformed
        jTabbedGestionarMaterias.setSelectedIndex(1);
    }//GEN-LAST:event_jBtnprinAsignarMateriDocenteActionPerformed


    private void jBtnBuscarDocenteAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarDocenteAsigActionPerformed
//        limpiarTablaDocente();
//        String dni = jTxtBuscarDniDocente.getText();
//        Docente docente = controlador.buscarDocente(dni);
//
//        modelo = (DefaultTableModel) jTableDocentesAsig.getModel(); // Reemplaza TableCliente con el nombre de tu JTable
//        Object[] ob = new Object[3]; // Ajusta el tamaño del array según los atributos de Alumno
//        ob[0] = docente.getDni();
//        ob[1] = docente.getNombre();
//        ob[2] = docente.getApellidoPaterno();
//        modelo.addRow(ob);
//        jTableDocentesAsig.setModel(modelo);
    }//GEN-LAST:event_jBtnBuscarDocenteAsigActionPerformed

    private void jButtonBuscarMateriaAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarMateriaAsigActionPerformed
//        limpiarTablaMateria();
//        String nombre = jTxtBuscarNombreMateria.getText();
//        Materia materia = controlador.buscarMateria(nombre);
//
//        modelo2 = (DefaultTableModel) jTableMateriaAsig.getModel();
//        Object[] ob = new Object[2];
//        ob[0] = materia.getId();
//        ob[1] = materia.getNombre();
//
//        modelo2.addRow(ob);
//        jTableMateriaAsig.setModel(modelo2);
    }//GEN-LAST:event_jButtonBuscarMateriaAsigActionPerformed

    private void jTableDocentesAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDocentesAsigMouseClicked

//        int fila = jTableDocentesAsig.rowAtPoint(evt.getPoint());
//        jTxtDniDocenteAsig.setText(String.valueOf(jTableDocentesAsig.getValueAt(fila, 0)));
//        jTxtNombreAsig.setText(String.valueOf(jTableDocentesAsig.getValueAt(fila, 1)));
//        jTxtApPaternoAsig.setText(String.valueOf(jTableDocentesAsig.getValueAt(fila, 2)));


    }//GEN-LAST:event_jTableDocentesAsigMouseClicked

    private void jTableMateriaAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMateriaAsigMouseClicked
//        int fila = jTableMateriaAsig.rowAtPoint(evt.getPoint());
//        jTxtIdAsig.setText(String.valueOf(jTableMateriaAsig.getValueAt(fila, 0)));
//        jTxtNombreAsigCurso.setText(String.valueOf(jTableMateriaAsig.getValueAt(fila, 1)));

    }//GEN-LAST:event_jTableMateriaAsigMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        String docenteDni = jTxtDniDocenteAsig.getText();
//        int idMateria = Integer.parseInt(jTxtIdAsig.getText());
//        controlador.registrarDocenteMateria(docenteDni, idMateria);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarRegistroActionPerformed

//        int idRegistro = Integer.parseInt(jTxtRegistroMateriaDocente.getText());
//        //DocenteMateria dM=controlador.buscarDocenteMateria(idRegistro);
//        controlador.eliminarDocenteMateria(idRegistro);


    }//GEN-LAST:event_jBtnEliminarRegistroActionPerformed

    private void jTableListaMateriasDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMateriasDocenteMouseClicked

//        int fila = jTableListaMateriasDocente.rowAtPoint(evt.getPoint());
//        jTxtRegistroMateriaDocente.setText(String.valueOf(jTableListaMateriasDocente.getValueAt(fila, 0)));
    }//GEN-LAST:event_jTableListaMateriasDocenteMouseClicked

    private void jTabbedGestionarMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedGestionarMateriasMouseClicked
        cargarTablaDocente();
        cargarTablaMateria();
        cargarTablaMateriaDocente();
    }//GEN-LAST:event_jTabbedGestionarMateriasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarDocenteAsig;
    private javax.swing.JButton jBtnEliminarRegistro;
    private javax.swing.JButton jBtnListarMaterias;
    private javax.swing.JButton jBtnPrinListarMatDoc;
    private javax.swing.JButton jBtnPrinRegistrarMateria;
    private javax.swing.JButton jBtnprinAsignarMateriDocente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarMateriaAsig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAsignarDocente;
    private javax.swing.JPanel jPanelListaMateriasDocente;
    private javax.swing.JPanel jPanelMenuGestion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedGestionarMaterias;
    private javax.swing.JTable jTableDocentesAsig;
    private javax.swing.JTable jTableListaMateriasDocente;
    private javax.swing.JTable jTableMateriaAsig;
    private javax.swing.JTextField jTxtApPaternoAsig;
    private javax.swing.JTextField jTxtBuscarDniDocente;
    private javax.swing.JTextField jTxtBuscarNombreMateria;
    private javax.swing.JTextField jTxtDniDocenteAsig;
    private javax.swing.JTextField jTxtIdAsig;
    private javax.swing.JTextField jTxtNombreAsig;
    private javax.swing.JTextField jTxtNombreAsigCurso;
    private javax.swing.JTextField jTxtRegistroMateriaDocente;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaMateria() {
//        limpiarTablaMateria();
//        List<Materia> listaMateria = controlador.listarMaterias(); // Reemplaza con tu instancia del DAO
//        modelo2 = (DefaultTableModel) jTableMateriaAsig.getModel(); // Reemplaza TableCliente con el nombre de tu JTable
//        Object[] ob = new Object[2]; // Ajusta el tamaño del array según los atributos de Alumno
//
//        for (int i = 0; i < listaMateria.size(); i++) {
//            Materia materia = listaMateria.get(i);
//            ob[0] = materia.getId();
//            ob[1] = materia.getNombre();
//            modelo2.addRow(ob);
//        }
//        jTableMateriaAsig.setModel(modelo2);
    }

    private void limpiarTablaMateria() {
//        modelo2 = (DefaultTableModel) jTableMateriaAsig.getModel();
//        int rowCount = modelo2.getRowCount();
//
//        for (int i = rowCount - 1; i >= 0; i--) {
//            modelo2.removeRow(i);
//        }
    }

    private void cargarTablaDocente() {
//        limpiarTablaDocente();
//        List<Docente> listaDocente = controlador.listarDocentes(); // Reemplaza con tu instancia del DAO
//        modelo = (DefaultTableModel) jTableDocentesAsig.getModel(); // Reemplaza TableCliente con el nombre de tu JTable
//        Object[] ob = new Object[3]; // Ajusta el tamaño del array según los atributos de Alumno
//
//        for (int i = 0; i < listaDocente.size(); i++) {
//            Docente docente = listaDocente.get(i);
//            ob[0] = docente.getDni();
//            ob[1] = docente.getNombre();
//            ob[2] = docente.getApellidoPaterno();
//
//            modelo.addRow(ob);
//        }
//        jTableDocentesAsig.setModel(modelo);
    }

    private void limpiarTablaDocente() {
//        modelo = (DefaultTableModel) jTableDocentesAsig.getModel();
//        int rowCount = modelo.getRowCount();
//
//        for (int i = rowCount - 1; i >= 0; i--) {
//            modelo.removeRow(i);
//
//        }
    }

    private void cargarTablaMateriaDocente() {
//        limpiarTablaMateriaDocente();
//
//        List<DocenteMateria> lDM = controlador.listarDocenteMaterias(); 
//        
//        modelo3 = (DefaultTableModel) jTableListaMateriasDocente.getModel(); // Reemplaza TableCliente con el nombre de tu JTable
//        Object[] ob = new Object[4]; // Ajusta el tamaño del array según los atributos de Alumno
//
//        for (int i = 0; i < lDM.size(); i++) {
//            DocenteMateria listDM = lDM.get(i);
//            Docente docente = controlador.buscarDocente(listDM.getIdDocente());
//            Materia materia = controlador.buscarMateria(listDM.getIdMateria());
//            ob[0] = listDM.getId();
//            ob[1] = docente.getDni();
//            ob[2] = docente.getNombre();
//            ob[3] = materia.getNombre();
//            modelo3.addRow(ob);
//        }
//        jTableListaMateriasDocente.setModel(modelo3);
    }

    private void limpiarTablaMateriaDocente() {
//        modelo = (DefaultTableModel) jTableListaMateriasDocente.getModel();
//        int rowCount = modelo.getRowCount();
//
//        for (int i = rowCount - 1; i >= 0; i--) {
//            modelo.removeRow(i);
//
//        }
    }

}
