/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.doomTechnologies.view;

import com.doomTechnologies.Controller.entitiescontroller.*;
import com.doomTechnologies.model.entities.Alumno;
import com.doomTechnologies.model.entities.Apoderado;
import com.doomTechnologies.model.entities.Usuario;
import com.doomTechnologies.utils.Validar;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class GestionarAlumnos extends JPanel {

    /**
     * Creates new form GestionarAlumnos
     */
    private final AlumnoController alumnoController = new AlumnoController();
    private final ApoderadoController apoderadoController = new ApoderadoController();
    private final GradoController gradoController = new GradoController();
    private final SeccionController seccionController = new SeccionController();
    private final UsuarioController usuarioController = new  UsuarioController();

    DefaultTableModel modelo = new DefaultTableModel();

    public GestionarAlumnos() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGestionarAl = new JTabbedPane();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel3 = new JLabel();
        jButtonListaAlumnos = new JButton();
        jPanel3 = new JPanel();
        jLabel4 = new JLabel();
        jButtonEditarAlumno = new JButton();
        jLabel1 = new JLabel();
        jPanel4 = new JPanel();
        jLabel2 = new JLabel();
        jButtonRegistrarAlumno = new JButton();
        jPanel6 = new JPanel();
        jTxtApPaterno = new JTextField();
        jTxtDni = new JTextField();
        jTxtApMaterno = new JTextField();
        jLabel10 = new JLabel();
        jTxtDireccion = new JTextField();
        jLabel11 = new JLabel();
        jDateChooserFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel17 = new JLabel();
        jLabel18 = new JLabel();
        jTxtNombre = new JTextField();
        jButtonRegistrarMatricula = new JButton();
        jComboBoGrado = new JComboBox<>();
        jComboBoxSeccion = new JComboBox<>();
        jComboBoxGenero = new JComboBox<>();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        jLabel19 = new JLabel();
        jLabel20 = new JLabel();
        jTxtNombreApoderado = new JTextField();
        jLabel21 = new JLabel();
        jLabel22 = new JLabel();
        jTxtApMaternoApoderado = new JTextField();
        jLabel23 = new JLabel();
        jTxtApPaternoApoderado = new JTextField();
        jTxtTelefonoApoderado = new JTextField();
        jLabel24 = new JLabel();
        jTxtTelefonoAlumno = new JTextField();
        jPanel5 = new JPanel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jTextFieldDni = new JTextField();
        jTextFieldNombre = new JTextField();
        jTextFieldApPaterno = new JTextField();
        jTextFieldApMaterno = new JTextField();
        jScrollPane1 = new JScrollPane();
        jTableAlumnos = new JTable();
        jButtonEliminar = new JButton();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jPanel7 = new JPanel();
        jTxtApPaternoEdit = new JTextField();
        jTxtDniEdit = new JTextField();
        jTxtApMaternoEdit = new JTextField();
        jLabel25 = new JLabel();
        jTxtDireccionEdit = new JTextField();
        jLabel26 = new JLabel();
        jDateChooserFechaNacEdit = new com.toedter.calendar.JDateChooser();
        jLabel27 = new JLabel();
        jLabel28 = new JLabel();
        jLabel29 = new JLabel();
        jLabel30 = new JLabel();
        jLabel31 = new JLabel();
        jTxtNombreEdit = new JTextField();
        jButtonEditarRegistro = new JButton();
        jComboBoGradoEdit = new JComboBox<>();
        jComboBoxSeccionEdit = new JComboBox<>();
        jComboBoxGeneroEdit = new JComboBox<>();
        jLabel32 = new JLabel();
        jLabel33 = new JLabel();
        jLabel34 = new JLabel();
        jLabel35 = new JLabel();
        jTxtNombreApoderadoEdit = new JTextField();
        jLabel36 = new JLabel();
        jLabel37 = new JLabel();
        jTxtApMaternoApoderadoEdit = new JTextField();
        jLabel38 = new JLabel();
        jTxtApPaternoApoderadoEdit = new JTextField();
        jTxtTelefonoApoderadoEdit = new JTextField();
        jLabel39 = new JLabel();
        jTxtTelefonoAlumnoEdit = new JTextField();
        jButtonBuscarDniAlumnoEdit = new JButton();

        setMinimumSize(new java.awt.Dimension(928, 721));

        jTabbedPaneGestionarAl.setMinimumSize(new java.awt.Dimension(928, 721));
        jTabbedPaneGestionarAl.setPreferredSize(new java.awt.Dimension(928, 721));
        jTabbedPaneGestionarAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneGestionarAlMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("LISTA ALUMNOS");

        jButtonListaAlumnos.setText("LISTA DE ALUMNOS");
        jButtonListaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaAlumnosActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonListaAlumnos, GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListaAlumnos, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("EDITAR");

        jButtonEditarAlumno.setText("EDITAR");
        jButtonEditarAlumno.setMaximumSize(new java.awt.Dimension(75, 44));
        jButtonEditarAlumno.setMinimumSize(new java.awt.Dimension(75, 44));
        jButtonEditarAlumno.setPreferredSize(new java.awt.Dimension(75, 44));
        jButtonEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAlumnoActionPerformed(evt);
            }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jButtonEditarAlumno, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditarAlumno, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("GESITONAR ALUMNOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("REGISTRO");

        jButtonRegistrarAlumno.setText("REGISTRAR ALUMNO");
        jButtonRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarAlumnoActionPerformed(evt);
            }
        });

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(jButtonRegistrarAlumno, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistrarAlumno, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPaneGestionarAl.addTab("Menu Gestion", jPanel1);

        jTxtApPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApPaternoActionPerformed(evt);
            }
        });

        jTxtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDniActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setText("Genero");

        jLabel12.setText("Direccion");

        jLabel13.setText("Grado");

        jLabel14.setText("Seccion");

        jLabel17.setText("Telefono/Celular");

        jLabel18.setText("Nombre");

        jButtonRegistrarMatricula.setText("Registrar Matricula");
        jButtonRegistrarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarMatriculaActionPerformed(evt);
            }
        });

        jComboBoGrado.setModel(new DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoGradoActionPerformed(evt);
            }
        });

        jComboBoxSeccion.setModel(new DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));

        jComboBoxGenero.setModel(new DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel15.setText("DNI");

        jLabel16.setText("Apellido paterno");

        jLabel19.setText("Apellido Materno");

        jLabel20.setText("Apoderado");

        jLabel21.setText("Apellido Paterno");

        jLabel22.setText("Apelñlido Materno");

        jLabel23.setText("Nombre :");

        jLabel24.setText("Telefono/Celular");

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtDni)
                    .addComponent(jTxtApPaterno)
                    .addComponent(jTxtApMaterno)
                    .addComponent(jTxtDireccion)
                    .addComponent(jDateChooserFechaNac, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jTxtTelefonoAlumno)
                    .addComponent(jLabel17, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jTxtNombre)
                    .addComponent(jLabel18, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jComboBoxGenero, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtTelefonoApoderado)
                    .addComponent(jLabel24, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jTxtNombreApoderado, GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtApMaternoApoderado)
                    .addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtApPaternoApoderado, GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrarMatricula, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoGrado, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxSeccion, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDni, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNombre, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jComboBoGrado, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSeccion)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTxtApPaterno, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApMaterno, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jComboBoxGenero, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserFechaNac, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDireccion, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNombreApoderado, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTxtApPaternoApoderado, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApMaternoApoderado, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTelefonoApoderado, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTelefonoAlumno, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarMatricula, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPaneGestionarAl.addTab("Registro", jPanel6);

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellido Paterno");

        jLabel7.setText("Apellido Materno");

        jTextFieldDni.setEditable(false);
        jTextFieldDni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldApPaterno.setEditable(false);

        jTextFieldApMaterno.setEditable(false);

        jTableAlumnos.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Ap. Paterno", "Ap. Materno", "Genero", "Nacimiento", "Direccion", "Telefono", "Grado", "Seccion", "Apoderado"
            }
        ));
        jTableAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlumnos);

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText("Lista De Alumnos");

        jLabel9.setText("DNI");

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDni, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldApPaterno, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldApMaterno, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDni, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApPaterno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApMaterno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButtonEliminar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );

        jTabbedPaneGestionarAl.addTab("Lista De Registro", jPanel5);

        jTxtApPaternoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApPaternoEditActionPerformed(evt);
            }
        });

        jTxtDniEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDniEditActionPerformed(evt);
            }
        });

        jLabel25.setText("Fecha de nacimiento");

        jLabel26.setText("Genero");

        jLabel27.setText("Direccion");

        jLabel28.setText("Grado");

        jLabel29.setText("Seccion");

        jLabel30.setText("Telefono/Celular");

        jLabel31.setText("Nombre");

        jButtonEditarRegistro.setText("Editar Registro");
        jButtonEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarRegistroActionPerformed(evt);
            }
        });

        jComboBoGradoEdit.setModel(new DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoGradoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoGradoEditActionPerformed(evt);
            }
        });

        jComboBoxSeccionEdit.setModel(new DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));

        jComboBoxGeneroEdit.setModel(new DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel32.setText("DNI");

        jLabel33.setText("Apellido paterno");

        jLabel34.setText("Apellido Materno");

        jLabel35.setText("Apoderado");

        jLabel36.setText("Apellido Paterno");

        jLabel37.setText("Apelñlido Materno");

        jLabel38.setText("Nombre :");

        jLabel39.setText("Telefono/Celular");

        jButtonBuscarDniAlumnoEdit.setText("Buscar");
        jButtonBuscarDniAlumnoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDniAlumnoEditActionPerformed(evt);
            }
        });

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtApPaternoEdit)
                    .addComponent(jTxtApMaternoEdit)
                    .addComponent(jTxtDireccionEdit)
                    .addComponent(jDateChooserFechaNacEdit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jTxtTelefonoAlumnoEdit)
                    .addComponent(jLabel30, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jTxtNombreEdit)
                    .addComponent(jLabel31, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jComboBoxGeneroEdit, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTxtDniEdit, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarDniAlumnoEdit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(104, 104, 104)
                .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtTelefonoApoderadoEdit)
                    .addComponent(jLabel39, GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jTxtNombreApoderadoEdit, GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtApMaternoApoderadoEdit)
                    .addComponent(jLabel28, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel37, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtApPaternoApoderadoEdit, GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditarRegistro, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoGradoEdit, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxSeccionEdit, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel32, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDniEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarDniAlumnoEdit))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNombreEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel28, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jComboBoGradoEdit, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSeccionEdit)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTxtApPaternoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApMaternoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jComboBoxGeneroEdit, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserFechaNacEdit, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDireccionEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel35, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNombreApoderadoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTxtApPaternoApoderadoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApMaternoApoderadoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel39, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTelefonoApoderadoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTelefonoAlumnoEdit, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditarRegistro, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPaneGestionarAl.addTab("Editar Registro", jPanel7);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGestionarAl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGestionarAl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAlumnoActionPerformed
        jTabbedPaneGestionarAl.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonEditarAlumnoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTableAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlumnosMouseClicked
        int fila = jTableAlumnos.rowAtPoint(evt.getPoint());

        jTextFieldDni.setText(String.valueOf(jTableAlumnos.getValueAt(fila, 0)));
        jTextFieldNombre.setText(String.valueOf(jTableAlumnos.getValueAt(fila, 1)));
        jTextFieldApPaterno.setText(String.valueOf(jTableAlumnos.getValueAt(fila, 2)));
        jTextFieldApMaterno.setText(String.valueOf(jTableAlumnos.getValueAt(fila, 3)));
    }//GEN-LAST:event_jTableAlumnosMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String dni = jTextFieldDni.getText();
        if (dni.isEmpty() || !Validar.isDNI(dni)) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un alumno válido en la tabla");
        } else {
            alumnoController.eliminarAlumno(dni);
            JOptionPane.showMessageDialog(null, "Alumno eliminado");
            cargarTabla();
        }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTxtApPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApPaternoActionPerformed

    private void jTxtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDniActionPerformed

    private void jButtonRegistrarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarMatriculaActionPerformed

// En el método jButtonRegistrarMatriculaActionPerformed
String dni = jTxtDni.getText();
String nombre = jTxtNombre.getText();
String apPaterno = jTxtApPaterno.getText();
String apMaterno = jTxtApMaterno.getText();
String direccion = jTxtDireccion.getText();
String telefonoAlumno = jTxtTelefonoAlumno.getText();
char genero = jComboBoxGenero.getSelectedItem().toString().charAt(0);
Date fechaNacimiento = jDateChooserFechaNac.getDate();
int gradoId = jComboBoGrado.getSelectedIndex() + 1;
int seccionId = jComboBoxSeccion.getSelectedIndex() + 1;

// Datos del apoderado
String nombreApoderado = jTxtNombreApoderado.getText();
String apPaternoApoderado = jTxtApPaternoApoderado.getText();
String apMaternoApoderado = jTxtApMaternoApoderado.getText();
String telefonoApoderado = jTxtTelefonoApoderado.getText();

Apoderado nuevoApoderado = Apoderado.builder()
        .id(0)
        .nombre(nombreApoderado)
        .apellidoPaterno(apPaternoApoderado)
        .apellidoMaterno(apMaternoApoderado)
        .telefono(telefonoApoderado)
        .build();

if (Validar.isNotEmpty(nombreApoderado) && Validar.isNotEmpty(apPaternoApoderado) && Validar.isNotEmpty(apMaternoApoderado) && Validar.isNotEmpty(telefonoApoderado)) {
    int apoderadoId = apoderadoController.registrarApoderadoRetornaID(nuevoApoderado);

    if (fechaNacimiento != null) {
        // Crear el usuario
        Usuario nuevoUsuario = Usuario.builder()
                .username(dni)
                .password(dni)
                .email("")
                .rolId(3)
                .build();
        if (usuarioController.regitrarUsuario(nuevoUsuario)) {
            // Crear el alumno con el ID del apoderado y el ID del usuario
            int idUsuario = usuarioController.buscarUsuarioPorUsername(nuevoUsuario.getUsername()).getId();
            Alumno alumno = Alumno.builder()
                    .dni(dni)
                    .nombre(nombre)
                    .apellidoPaterno(apPaterno)
                    .apellidoMaterno(apMaterno)
                    .genero(genero)
                    .fechaNacimiento(fechaNacimiento)
                    .direccion(direccion)
                    .telefono(telefonoAlumno)
                    .gradoId(gradoId)
                    .seccionId(seccionId)
                    .apoderadoId(apoderadoId)
                    .usuarioId(idUsuario)
                    .build();
            alumnoController.registrarAlumno(alumno);
            JOptionPane.showMessageDialog(null, "Alumno registrado");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "El usuario ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha de nacimiento.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "Datos del apoderado no válidos.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButtonRegistrarMatriculaActionPerformed

    private void jComboBoGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoGradoActionPerformed

    private void jTxtApPaternoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApPaternoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApPaternoEditActionPerformed

    private void jTxtDniEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDniEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDniEditActionPerformed

    private void jButtonEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarRegistroActionPerformed

        // Validate Apoderado fields
        if (!Validar.isNotEmpty(jTxtNombreApoderadoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El nombre del apoderado no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isNotEmpty(jTxtApPaternoApoderadoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El apellido paterno del apoderado no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isNotEmpty(jTxtApMaternoApoderadoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El apellido materno del apoderado no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isPhoneNumber(jTxtTelefonoApoderadoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El teléfono del apoderado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate Alumno fields
        if (!Validar.isNotEmpty(jTxtNombreEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El nombre del alumno no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isNotEmpty(jTxtApPaternoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El apellido paterno del alumno no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isNotEmpty(jTxtApMaternoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El apellido materno del alumno no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jComboBoxGeneroEdit.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "El género del alumno no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jDateChooserFechaNacEdit.getDate() == null) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento del alumno no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isNotEmpty(jTxtDireccionEdit.getText())) {
            JOptionPane.showMessageDialog(this, "La dirección del alumno no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validar.isPhoneNumber(jTxtTelefonoAlumnoEdit.getText())) {
            JOptionPane.showMessageDialog(this, "El teléfono del alumno no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jComboBoGradoEdit.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "El grado del alumno no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jComboBoxSeccionEdit.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "La sección del alumno no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Proceed with updating Apoderado and Alumno
        Alumno alumno = alumnoController.buscarAlumno(jTxtDniEdit.getText());
        Apoderado apoderado = apoderadoController.buscarApoderado(alumno.getApoderadoId());

        apoderado.setNombre(jTxtNombreApoderadoEdit.getText());
        apoderado.setApellidoPaterno(jTxtApPaternoApoderadoEdit.getText());
        apoderado.setApellidoMaterno(jTxtApMaternoApoderadoEdit.getText());
        apoderado.setTelefono(jTxtTelefonoApoderadoEdit.getText());
        apoderadoController.modificarApoderado(apoderado);

        alumno.setNombre(jTxtNombreEdit.getText());
        alumno.setApellidoPaterno(jTxtApPaternoEdit.getText());
        alumno.setApellidoMaterno(jTxtApMaternoEdit.getText());
        alumno.setGenero(jComboBoxGeneroEdit.getSelectedItem().toString().charAt(0));
        alumno.setFechaNacimiento(jDateChooserFechaNacEdit.getDate());
        alumno.setDireccion(jTxtDireccionEdit.getText());
        alumno.setTelefono(jTxtTelefonoAlumnoEdit.getText());
        alumno.setGradoId(jComboBoGradoEdit.getSelectedIndex() + 1);
        alumno.setSeccionId(jComboBoxSeccionEdit.getSelectedIndex() + 1);

        if(alumnoController.modificarAlumno(alumno)){
            JOptionPane.showMessageDialog(this, "Alumno y apoderado actualizados correctamente.");
        }

    }//GEN-LAST:event_jButtonEditarRegistroActionPerformed

    private void jComboBoGradoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoGradoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoGradoEditActionPerformed

    private void jButtonRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarAlumnoActionPerformed
        jTabbedPaneGestionarAl.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonRegistrarAlumnoActionPerformed

    private void jButtonListaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaAlumnosActionPerformed
        jTabbedPaneGestionarAl.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonListaAlumnosActionPerformed

    private void jButtonBuscarDniAlumnoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDniAlumnoEditActionPerformed
        String dni = jTxtDniEdit.getText();
        Alumno alumno = alumnoController.buscarAlumno(dni);

        if (alumno != null) {
            jTxtNombreEdit.setText(alumno.getNombre());
            jTxtApPaternoEdit.setText(alumno.getApellidoPaterno());
            jTxtApMaternoEdit.setText(alumno.getApellidoMaterno());
            char genero = alumno.getGenero();
            if (genero == 'M') {
                jComboBoxGeneroEdit.setSelectedIndex(0);
            } else if (genero == 'F') {
                jComboBoxGeneroEdit.setSelectedIndex(1);
            }
            jDateChooserFechaNacEdit.setDate(alumno.getFechaNacimiento());
            jTxtDireccionEdit.setText(alumno.getDireccion());
            jTxtTelefonoAlumnoEdit.setText(alumno.getTelefono());
            jComboBoGradoEdit.setSelectedIndex(alumno.getGradoId() - 1);
            jComboBoxSeccionEdit.setSelectedIndex(alumno.getSeccionId() - 1);

            Apoderado apoderado = apoderadoController.buscarApoderado(alumno.getApoderadoId());
            if (apoderado != null) {
                jTxtNombreApoderadoEdit.setText(apoderado.getNombre());
                jTxtApPaternoApoderadoEdit.setText(apoderado.getApellidoPaterno());
                jTxtApMaternoApoderadoEdit.setText(apoderado.getApellidoMaterno());
                jTxtTelefonoApoderadoEdit.setText(apoderado.getTelefono());
            } else {
                JOptionPane.showMessageDialog(this, "Apoderado no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Alumno no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonBuscarDniAlumnoEditActionPerformed

    private void jTabbedPaneGestionarAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneGestionarAlMouseClicked
        cargarTabla();
    }//GEN-LAST:event_jTabbedPaneGestionarAlMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonBuscarDniAlumnoEdit;
    private JButton jButtonEditarAlumno;
    private JButton jButtonEditarRegistro;
    private JButton jButtonEliminar;
    private JButton jButtonListaAlumnos;
    private JButton jButtonRegistrarAlumno;
    private JButton jButtonRegistrarMatricula;
    private JComboBox<String> jComboBoGrado;
    private JComboBox<String> jComboBoGradoEdit;
    private JComboBox<String> jComboBoxGenero;
    private JComboBox<String> jComboBoxGeneroEdit;
    private JComboBox<String> jComboBoxSeccion;
    private JComboBox<String> jComboBoxSeccionEdit;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNac;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacEdit;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel3;
    private JLabel jLabel30;
    private JLabel jLabel31;
    private JLabel jLabel32;
    private JLabel jLabel33;
    private JLabel jLabel34;
    private JLabel jLabel35;
    private JLabel jLabel36;
    private JLabel jLabel37;
    private JLabel jLabel38;
    private JLabel jLabel39;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JScrollPane jScrollPane1;
    private JTabbedPane jTabbedPaneGestionarAl;
    private JTable jTableAlumnos;
    private JTextField jTextFieldApMaterno;
    private JTextField jTextFieldApPaterno;
    private JTextField jTextFieldDni;
    private JTextField jTextFieldNombre;
    private JTextField jTxtApMaterno;
    private JTextField jTxtApMaternoApoderado;
    private JTextField jTxtApMaternoApoderadoEdit;
    private JTextField jTxtApMaternoEdit;
    private JTextField jTxtApPaterno;
    private JTextField jTxtApPaternoApoderado;
    private JTextField jTxtApPaternoApoderadoEdit;
    private JTextField jTxtApPaternoEdit;
    private JTextField jTxtDireccion;
    private JTextField jTxtDireccionEdit;
    private JTextField jTxtDni;
    private JTextField jTxtDniEdit;
    private JTextField jTxtNombre;
    private JTextField jTxtNombreApoderado;
    private JTextField jTxtNombreApoderadoEdit;
    private JTextField jTxtNombreEdit;
    private JTextField jTxtTelefonoAlumno;
    private JTextField jTxtTelefonoAlumnoEdit;
    private JTextField jTxtTelefonoApoderado;
    private JTextField jTxtTelefonoApoderadoEdit;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        jTxtNombre.setText("");
        jTxtDni.setText("");
        jTxtApPaterno.setText("");
        jTxtApMaterno.setText("");
        jTxtDireccion.setText("");
        jTxtTelefonoAlumno.setText("");
        jComboBoxGenero.setSelectedIndex(0); // Selecciona el primer elemento del JComboBox
        jDateChooserFechaNac.setDate(null);
        jComboBoGrado.setSelectedIndex(0); // Selecciona el primer elemento del JComboBox
        jComboBoxSeccion.setSelectedIndex(0); // Selecciona el primer elemento del JComboBox

        jTxtNombreApoderado.setText("");
        jTxtApPaternoApoderado.setText("");
        jTxtApMaternoApoderado.setText("");
        jTxtTelefonoApoderado.setText("");
    }

    private void cargarTabla() {

        limpiarTabla();
        List<Alumno> listaAlumnos = alumnoController.listarAlumnos(); // Reemplaza con tu instancia del DAO
        modelo = (DefaultTableModel) jTableAlumnos.getModel(); // Reemplaza TableCliente con el nombre de tu JTable
        Object[] ob = new Object[12]; // Ajusta el tamaño del array según los atributos de Alumno

        for (int i = 0; i < listaAlumnos.size(); i++) {
            Alumno alumno = listaAlumnos.get(i);
            ob[0] = alumno.getDni();
            ob[1] = alumno.getNombre();
            ob[2] = alumno.getApellidoPaterno();
            ob[3] = alumno.getApellidoMaterno();
            ob[4] = alumno.getGenero();
            ob[5] = alumno.getFechaNacimiento();
            ob[6] = alumno.getDireccion();
            ob[7] = alumno.getTelefono();
            ob[8] = gradoController.buscarGrado(alumno.getGradoId()).getNombre();
            ob[9] = seccionController.buscarSeccion(alumno.getSeccionId()).getNombre();
            ob[10] = apoderadoController.buscarApoderado(alumno.getApoderadoId()).getNombre();
            modelo.addRow(ob);
        }
        jTableAlumnos.setModel(modelo);
    }

    private void limpiarTabla() {
        modelo = (DefaultTableModel) jTableAlumnos.getModel();
        int rowCount = modelo.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

}
